version: '3.8'

services:
  web:
    build: .
    ports:
      - "5056:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://user:password@db:5432/todo_db
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: